apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault
  namespace: test
  labels:
    app: vault-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:  
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault-deployment
  name: vault
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-deployment
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK 
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token
        volumeMounts:
          - mountPath: /var/run/vault
            name: vault
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault-deployment
  namespace: test
spec:
  ports:
    - name: vault
      port: 80
      targetPort: 8200
  selector:
    app: vault-deployment
  type: LoadBalancer